version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      actions-all:
        patterns: ["*"]
    labels: [dependencies, github-actions]

  - package-ecosystem: npm
    directory: "/tools/editor-bundle"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      npm-minor-patch:
        update-types: [minor, patch]
      npm-major:
        update-types: [major]
    labels: [dependencies, npm]

  - package-ecosystem: npm
    directory: "/tools/test"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      npm-minor-patch:
        update-types: [minor, patch]
      npm-major:
        update-types: [major]
    labels: [dependencies, npm]
